---
- name: Install docker from repository
  apt:
    name: docker.io
    state: present

- name: Install pip3
  package:
    update_cache: yes
    name: python3-pip
    state: latest

- name: Install docker SDK for python
  pip:
    name: docker
    executable: pip3

- name: Create directory for project
  file: path=/opt/docker state=directory

- name: Copy NGINX Dockerfile
  copy:
    src: /home/{{ OWNER }}/final/roles/nginx/files/Dockerfile
    dest: /opt/docker/nginx
    mode: 0755
    owner: root
    group: root

- name: Copy NGINX config
  copy:
    src: /home/{{ OWNER }}/final/roles/nginx/files/nginx.conf
    dest: /opt/docker/nginx
    mode: 0755
    owner: root
    group: root

- name: Build NGINX docker
  community.docker.docker_image:
    build:
      path: /opt/docker/nginx 
    name: nginx
    tag: v2
    source: build

- name: Run NGINX
  docker_container:
    name: nginx
    image: nginx:v2
    state: started
    published_ports: "80:80"
    exposed_ports: 80
    networks:
      - name: flaskapp

