---
- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Install pip3
  package:
    update_cache: yes
    name: python3-pip
    state: latest

- name: Install Docker SDK
  pip:
    name: docker
    executable: pip3

- name: Create directory
  file:
    path: /opt/docker
    state: directory

- name: Create the directory for upload
  file:
    path: /home/{{ OWNER }}/files
    state: directory

- name: Clone github repository
  ansible.builtin.git:
    repo: https://github.com/pxty/flaskapp
    dest: /home/{{ OWNER }}/flaskapp
    clone: yes
    update: yes

- name: Write .env
  ansible.builtin.template:
    src: ./templates/env.j2
    dest: /home/{{ OWNER }}/flaskapp/.env
    owner: root
    group: root
    mode: '0755'

- name: Build image flaskapp
  community.docker.docker_image:
    name: flaskapp:exam
    build:
      path: /home/{{ OWNER }}/flaskapp
    source: build
    state: present

- name: Create the network
  community.docker.docker_network:
    name: flaskapp

- name: Run flaskapp1
  docker_container:
    name: flaskapp1
    image: flaskapp:exam
    state: started
    exposed_ports: 5000
    networks:
      - name: flaskapp

- name: Run flaskapp2
  docker_container:
    name: flaskapp2
    image: flaskapp:exam
    state: started
    exposed_ports: 5000
    networks:
      - name: flaskapp
